[package]
name = "SE-SASL2021-vv"
version = "0.1.0"
authors = ["Lars Vogtmann", "David Voigt <david.voigt1998@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
